#####################################
###### COLORSCHEME: PaperColor ######
#####################################

# Enable 256 colors, https://github.com/tmux/tmux/wiki/FAQ
# set -g default-terminal "tmux-256color"
# set -g default-terminal "screen-256color"
# https://superuser.com/questions/424086/what-is-the-difference-between-screen-256-color-and-xterm-256color
set -g default-terminal $TERM

BG1="#005f87"
BG2="#e4e4e4"
BG3="#0087af"
FG1="#444444"

set-option -g status "off"

set-option -g status-style bg=$BG1,fg=$FG1
set-option -g status-position bottom

# active window title colors
set-window-option -g window-status-current-style bg=$BG2,fg=$BG1 

# pane border
set-option -g pane-active-border-style fg=$BG3
set-option -g pane-border-style fg=$BG3

# message infos
set-option -g message-style bg=$BG1,fg=$BG2

# commands
set-option -g message-command-style bg=$BG1,fg=$FG1

# clock
set-window-option -g clock-mode-colour colour24 #blue

# bell
set-window-option -g window-status-bell-style fg=colour229,bg=colour88 #bg, red

#####################################
###### COLORSCHEME: PaperColor ######
#####################################

# Window numbers start at 1 instead of 0 to make switching easier
set -g base-index 1
setw -g pane-base-index 1

# Allow customizing tab names using bash precmd_functions
set-option -g allow-rename on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf; display-message "tmux reloaded"
set -g message-style 'fg=red,bg=default,bold'

# switch panes using Alt-arrow without prefix
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Increase the scrollback buffer to a higher limit than the default 2000 lines
set -g history-limit 100000
# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
# Enable vim keybinds to be used in copy mode
set-window-option -g mode-keys vi

# copy mode
setw -g mode-style 'fg=black,bg=yellow,bold'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

